import { describe, expect, it } from 'vitest';
import { flattenItems, parseManifest } from '../src/lib/manifest';
import { inferLectoraStructure, isLectoraPackage, prettify } from '../src/lib/structure';
import { encodeText } from '../src/lib/text';

// A miniature of how Lectora 19 publishes: one SCO, one resource per page
// listed in course order, and every image in one shared resource.
const pages = [
  'a001_student_dashboard.html',
  'a001_intro_screens_navigation.html',
  'a001_intro_screens_sound_check.html',
  'a001_safety_basics_welcome.html',
  'a001_safety_basics_let_s_review.html',
  'a001_safety_basics_when_you_don_t_listen.html',
  ...[1, 2].flatMap((m) => ['', ...[1, 2, 3, 4, 5].map((q) => `_q${q}`)].map((q) => `a001_test_module_${m}${q}.html`)),
  'a001_test_results.html',
];
const manifest = `<?xml version="1.0" encoding="UTF-8"?>
<!--GENERATED BY:  Lectora v.19.0.4 -->
<manifest identifier="CourseID" xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2" xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2">
  <organizations default="O"><organization identifier="O"><title>Course</title>
    <item identifier="I_A001" identifierref="A001"><title>Course</title></item>
  </organization></organizations>
  <resources>
    <resource identifier="A001" type="webcontent" adlcp:scormtype="sco" href="a001index.html"><file href="a001index.html"/>
      ${pages.map((_, i) => `<dependency identifierref="P_${i}"/>`).join('')}<dependency identifierref="R_images"/></resource>
    ${pages.map((p, i) => `<resource identifier="P_${i}" type="webcontent" adlcp:scormtype="asset"><file href="${p}"/></resource>`).join('\n')}
    <resource identifier="F_1" type="webcontent" adlcp:scormtype="asset"><file href="a001_toc1.html"/></resource>
    <resource identifier="R_images" type="webcontent" adlcp:scormtype="asset"><file href="images/logo.png"/><file href="images/welcome.png"/><file href="images/unused.png"/><file href="images/trans.gif"/></resource>
  </resources>
</manifest>`;

function build() {
  const files: Record<string, Uint8Array> = { 'imsmanifest.xml': encodeText(manifest), 'trivantis.js': encodeText('//'), 'a001index.html': encodeText('<html></html>'), 'a001_toc1.html': encodeText('<html></html>') };
  for (const p of pages) {
    const img = p.includes('welcome') ? 'images/welcome.png' : 'images/logo.png';
    files[p] = encodeText(`<html><head><title>Course</title></head><body><script>var image1 = new ObjImage('image1', null, '${img}');</script></body></html>`);
  }
  for (const f of ['images/logo.png', 'images/welcome.png', 'images/unused.png', 'images/trans.gif']) files[f] = new Uint8Array([1]);
  return files;
}

describe('Lectora structure from page names', () => {
  it('recovers chapters, sections and page titles in course order', () => {
    const files = build();
    expect(isLectoraPackage(manifest, files)).toBe(true);
    const s = inferLectoraStructure(parseManifest(manifest), files)!;
    expect(s.modules.map((m) => m.title)).toEqual(['Student', 'Intro Screens', 'Safety Basics', 'Test']);
    expect(s.modules[2].children.map((c) => c.title)).toEqual(['Welcome', "Let's Review", "When You Don't Listen"]);
    // The test chapter splits into its module sections; the results page stays a direct child.
    expect(s.modules[3].children.map((c) => c.title)).toEqual(['Module 1', 'Module 2', 'Results']);
    expect(s.modules[3].children[0].children).toHaveLength(6);
    expect(s.pageCount).toBe(pages.length);
    // TOC frames and the launch page aren't content pages.
    expect(flattenItems(s.modules).some((i) => i.href === 'a001_toc1.html' || i.href === 'a001index.html')).toBe(false);
  });

  it('assigns assets to chapters by what each page refers to', () => {
    const files = build();
    const s = inferLectoraStructure(parseManifest(manifest), files)!;
    const safety = s.modules[2];
    expect(s.index.itemFiles.get(safety.identifier)).toContain('images/welcome.png');
    expect(s.index.fileModules.get('images/welcome.png')!.map((m) => m.title)).toEqual(['Safety Basics']);
    expect(s.index.fileModules.get('images/logo.png')!.length).toBeGreaterThan(1);
    expect(s.index.unlisted).toContain('images/unused.png');
    expect(s.index.unlisted).toContain('a001_toc1.html');
  });

  it('restores apostrophes and keeps small words lower-case', () => {
    expect(prettify('let_s_review')).toBe("Let's Review");
    expect(prettify('the_people_you_work_with_everyday')).toBe('The People You Work with Everyday');
    expect(prettify('you_re_on_the_team')).toBe("You're on the Team");
  });
});
